version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    environment:
      - DB_HOST=${DB_HOST}    # change this when replacing MySQL contianer with another database
      - DB_USER=${DB_USER}    # change this when replacing MySQL contianer with another database
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 60s
      retries: 6

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:

volumes:
  db-data:
