name: entryTracker CI\CD

on:
  push:
    branches: [ "main" ]

env:
  REGION: "ap-south-1"


jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      # Part 1: Pull the application source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Part 2: Build the application: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the application in the background
      - name: Start app.py
        run: |
          nohup python app.py &

      # Part 3: Run unit tests
      - name: Test the application with curl
        run: |
          echo "Testing the application..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" http://localhost:5000)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error: Expected HTTP 200 but got $RESPONSE"
            cat response.txt
            exit 1
          fi
          echo "Test successful! Application returned HTTP 200."
          echo "Response from the application:"
          cat response.txt
          exit 0

      # Stop the app
      - name: Cleanup
        run: |
          pkill -f app.py || true

  E2E-Test-and-Deploy:
    needs: Build-and-Test
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout App
        uses: actions/checkout@v2

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      # Download .env from S3
      - name: Download .env file from S3
        run: |
          aws s3 cp s3://entytracker-cicd/.env .

      # Load environment variables
      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1
        with:
          path: '.'
          filenames: '.env'
          expand: true  

      # Deploy to Staging: Deploy Instance
      - name: Make scripts executable
        run: |
          sed -i 's/\r$//' scripts/run-instances.sh
          sed -i 's/\r$//' scripts/userdata.sh
          chmod +x scripts/run-instances.sh
      
      # Run run-instance.sh and user-da
      - name: Launch EC2 and wait
        run: bash scripts/run-instances.sh -u scripts/userdata.sh

      # Using SSM, Docker Compose up and test
      - name: Docker Compose up
        run: |
          echo "Executing E2E test script..."
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=[ \
              "echo 'Starting Docker Compose...'", \
              "docker compose up -d", \
              "echo 'Waiting for the application to be ready...'", \
              "MAX_RETRIES=15", \
              "RETRY_INTERVAL=1", \
              "for i in $(seq 1 $MAX_RETRIES); do if curl -s http://localhost:5000 > /dev/null; then echo 'Application is up and running!'; break; fi; echo 'Retry $i/$MAX_RETRIES: Application not ready yet. Retrying in $RETRY_INTERVAL second(s)...'; sleep $RETRY_INTERVAL; done", \
              "if ! curl -s http://localhost:5000 > /dev/null; then echo 'Error: Application did not start within the expected time.'; docker compose logs; exit 1; fi", \
            ] \
            --region ${{ env.REGION }}
